// Minimal hero data for Telegram Bot Edge Function (Deno runtime)
// Source of truth: src/data/heroes.ts
// Sync this file whenever heroes are added/modified in heroes.ts

export interface HeroDeno {
  id: string;
  name: string;
  roles: string[];
  damageType: 'Physical' | 'Magic' | 'True' | 'Mixed';
}

export const HEROES_DENO: Record<string, HeroDeno> = {
  // ===== FIGHTERS =====
  chou:        { id: 'chou',        name: 'Chou',        roles: ['Fighter'],              damageType: 'Physical' },
  balmond:     { id: 'balmond',     name: 'Balmond',     roles: ['Fighter'],              damageType: 'Physical' },
  bane:        { id: 'bane',        name: 'Bane',        roles: ['Fighter', 'Mage'],      damageType: 'Mixed'    },
  jawhead:     { id: 'jawhead',     name: 'Jawhead',     roles: ['Fighter'],              damageType: 'Physical' },
  alucard:     { id: 'alucard',     name: 'Alucard',     roles: ['Fighter', 'Assassin'],  damageType: 'Physical' },
  zilong:      { id: 'zilong',      name: 'Zilong',      roles: ['Fighter', 'Assassin'],  damageType: 'Physical' },
  freya:       { id: 'freya',       name: 'Freya',       roles: ['Fighter'],              damageType: 'Physical' },
  ruby:        { id: 'ruby',        name: 'Ruby',        roles: ['Fighter', 'Tank'],      damageType: 'Physical' },
  lapulapu:    { id: 'lapulapu',    name: 'Lapu-Lapu',   roles: ['Fighter'],              damageType: 'Physical' },
  roger:       { id: 'roger',       name: 'Roger',       roles: ['Fighter', 'Marksman'],  damageType: 'Physical' },
  argus:       { id: 'argus',       name: 'Argus',       roles: ['Fighter'],              damageType: 'Physical' },
  martis:      { id: 'martis',      name: 'Martis',      roles: ['Fighter'],              damageType: 'Physical' },
  aldous:      { id: 'aldous',      name: 'Aldous',      roles: ['Fighter'],              damageType: 'Physical' },
  leomord:     { id: 'leomord',     name: 'Leomord',     roles: ['Fighter'],              damageType: 'Physical' },
  thamuz:      { id: 'thamuz',      name: 'Thamuz',      roles: ['Fighter'],              damageType: 'True'     },
  minsitthar:  { id: 'minsitthar',  name: 'Minsitthar',  roles: ['Fighter'],              damageType: 'Physical' },
  badang:      { id: 'badang',      name: 'Badang',      roles: ['Fighter'],              damageType: 'Physical' },
  guinevere:   { id: 'guinevere',   name: 'Guinevere',   roles: ['Fighter'],              damageType: 'Magic'    },
  terizla:     { id: 'terizla',     name: 'Terizla',     roles: ['Fighter'],              damageType: 'Physical' },
  xborg:       { id: 'xborg',       name: 'X.Borg',      roles: ['Fighter'],              damageType: 'True'     },
  silvanna:    { id: 'silvanna',    name: 'Silvanna',    roles: ['Fighter'],              damageType: 'Magic'    },
  yu_zhong:    { id: 'yu_zhong',    name: 'Yu Zhong',    roles: ['Fighter'],              damageType: 'Physical' },
  khaleed:     { id: 'khaleed',     name: 'Khaleed',     roles: ['Fighter'],              damageType: 'Physical' },
  barats:      { id: 'barats',      name: 'Barats',      roles: ['Tank', 'Fighter'],      damageType: 'Physical' },
  paquito:     { id: 'paquito',     name: 'Paquito',     roles: ['Fighter'],              damageType: 'Physical' },
  phoveus:     { id: 'phoveus',     name: 'Phoveus',     roles: ['Fighter'],              damageType: 'Magic'    },
  aulus:       { id: 'aulus',       name: 'Aulus',       roles: ['Fighter'],              damageType: 'Physical' },
  yin:         { id: 'yin',         name: 'Yin',         roles: ['Fighter', 'Assassin'],  damageType: 'Physical' },
  julian:      { id: 'julian',      name: 'Julian',      roles: ['Fighter', 'Mage'],      damageType: 'Magic'    },
  arlott:      { id: 'arlott',      name: 'Arlott',      roles: ['Fighter', 'Assassin'],  damageType: 'Physical' },
  cici:        { id: 'cici',        name: 'Cici',        roles: ['Fighter'],              damageType: 'Mixed'    },
  dyrroth:     { id: 'dyrroth',     name: 'Dyrroth',     roles: ['Fighter'],              damageType: 'Physical' },
  hilda:       { id: 'hilda',       name: 'Hilda',       roles: ['Fighter', 'Tank'],      damageType: 'Physical' },
  alpha:       { id: 'alpha',       name: 'Alpha',       roles: ['Fighter'],              damageType: 'Physical' },
  sun:         { id: 'sun',         name: 'Sun',         roles: ['Fighter'],              damageType: 'Physical' },

  // ===== TANKS =====
  tigreal:     { id: 'tigreal',     name: 'Tigreal',     roles: ['Tank', 'Support'],      damageType: 'Physical' },
  akai:        { id: 'akai',        name: 'Akai',        roles: ['Tank', 'Support'],      damageType: 'Physical' },
  franco:      { id: 'franco',      name: 'Franco',      roles: ['Tank', 'Support'],      damageType: 'Physical' },
  minotaur:    { id: 'minotaur',    name: 'Minotaur',    roles: ['Tank', 'Support'],      damageType: 'Physical' },
  lolita:      { id: 'lolita',      name: 'Lolita',      roles: ['Tank', 'Support'],      damageType: 'Physical' },
  johnson:     { id: 'johnson',     name: 'Johnson',     roles: ['Tank'],                 damageType: 'Magic'    },
  gatotkaca:   { id: 'gatotkaca',   name: 'Gatotkaca',   roles: ['Tank', 'Fighter'],      damageType: 'Magic'    },
  grock:       { id: 'grock',       name: 'Grock',       roles: ['Tank'],                 damageType: 'Physical' },
  hylos:       { id: 'hylos',       name: 'Hylos',       roles: ['Tank'],                 damageType: 'Magic'    },
  uranus:      { id: 'uranus',      name: 'Uranus',      roles: ['Tank'],                 damageType: 'Magic'    },
  belerick:    { id: 'belerick',    name: 'Belerick',    roles: ['Tank'],                 damageType: 'Magic'    },
  khufra:      { id: 'khufra',      name: 'Khufra',      roles: ['Tank'],                 damageType: 'Physical' },
  esmeralda:   { id: 'esmeralda',   name: 'Esmeralda',   roles: ['Tank', 'Mage'],         damageType: 'Mixed'    },
  baxia:       { id: 'baxia',       name: 'Baxia',       roles: ['Tank'],                 damageType: 'Magic'    },
  masha:       { id: 'masha',       name: 'Masha',       roles: ['Tank', 'Fighter'],      damageType: 'Physical' },
  atlas:       { id: 'atlas',       name: 'Atlas',       roles: ['Tank', 'Support'],      damageType: 'Magic'    },
  gloo:        { id: 'gloo',        name: 'Gloo',        roles: ['Tank'],                 damageType: 'Magic'    },
  edith:       { id: 'edith',       name: 'Edith',       roles: ['Tank', 'Marksman'],     damageType: 'Magic'    },
  fredrinn:    { id: 'fredrinn',    name: 'Fredrinn',    roles: ['Tank', 'Fighter'],      damageType: 'Physical' },

  // ===== ASSASSINS =====
  saber:       { id: 'saber',       name: 'Saber',       roles: ['Assassin'],             damageType: 'Physical' },
  karina:      { id: 'karina',      name: 'Karina',      roles: ['Assassin'],             damageType: 'Magic'    },
  fanny:       { id: 'fanny',       name: 'Fanny',       roles: ['Assassin'],             damageType: 'Physical' },
  hayabusa:    { id: 'hayabusa',    name: 'Hayabusa',    roles: ['Assassin'],             damageType: 'Physical' },
  natalia:     { id: 'natalia',     name: 'Natalia',     roles: ['Assassin'],             damageType: 'Physical' },
  lancelot:    { id: 'lancelot',    name: 'Lancelot',    roles: ['Assassin'],             damageType: 'Physical' },
  helcurt:     { id: 'helcurt',     name: 'Helcurt',     roles: ['Assassin'],             damageType: 'Physical' },
  gusion:      { id: 'gusion',      name: 'Gusion',      roles: ['Assassin', 'Mage'],     damageType: 'Magic'    },
  selena:      { id: 'selena',      name: 'Selena',      roles: ['Assassin', 'Mage'],     damageType: 'Magic'    },
  hanzo:       { id: 'hanzo',       name: 'Hanzo',       roles: ['Assassin'],             damageType: 'Physical' },
  ling:        { id: 'ling',        name: 'Ling',        roles: ['Assassin'],             damageType: 'Physical' },
  benedetta:   { id: 'benedetta',   name: 'Benedetta',   roles: ['Assassin', 'Fighter'],  damageType: 'Physical' },
  mathilda:    { id: 'mathilda',    name: 'Mathilda',    roles: ['Support', 'Assassin'],  damageType: 'Magic'    },
  aamon:       { id: 'aamon',       name: 'Aamon',       roles: ['Assassin'],             damageType: 'Magic'    },
  joy:         { id: 'joy',         name: 'Joy',         roles: ['Assassin'],             damageType: 'Magic'    },
  nolan:       { id: 'nolan',       name: 'Nolan',       roles: ['Assassin'],             damageType: 'Physical' },
  suyou:       { id: 'suyou',       name: 'Suyou',       roles: ['Assassin', 'Fighter'],  damageType: 'Physical' },

  // ===== MAGES =====
  alice:       { id: 'alice',       name: 'Alice',       roles: ['Mage', 'Tank'],         damageType: 'Magic'    },
  nana:        { id: 'nana',        name: 'Nana',        roles: ['Mage', 'Support'],      damageType: 'Magic'    },
  eudora:      { id: 'eudora',      name: 'Eudora',      roles: ['Mage'],                 damageType: 'Magic'    },
  gord:        { id: 'gord',        name: 'Gord',        roles: ['Mage'],                 damageType: 'Magic'    },
  kagura:      { id: 'kagura',      name: 'Kagura',      roles: ['Mage'],                 damageType: 'Magic'    },
  cyclops:     { id: 'cyclops',     name: 'Cyclops',     roles: ['Mage'],                 damageType: 'Magic'    },
  aurora:      { id: 'aurora',      name: 'Aurora',      roles: ['Mage'],                 damageType: 'Magic'    },
  vexana:      { id: 'vexana',      name: 'Vexana',      roles: ['Mage'],                 damageType: 'Magic'    },
  harley:      { id: 'harley',      name: 'Harley',      roles: ['Mage', 'Assassin'],     damageType: 'Magic'    },
  odette:      { id: 'odette',      name: 'Odette',      roles: ['Mage'],                 damageType: 'Magic'    },
  zhask:       { id: 'zhask',       name: 'Zhask',       roles: ['Mage'],                 damageType: 'Magic'    },
  pharsa:      { id: 'pharsa',      name: 'Pharsa',      roles: ['Mage'],                 damageType: 'Magic'    },
  valir:       { id: 'valir',       name: 'Valir',       roles: ['Mage'],                 damageType: 'Magic'    },
  change:      { id: 'change',      name: "Chang'e",     roles: ['Mage'],                 damageType: 'Magic'    },
  vale:        { id: 'vale',        name: 'Vale',        roles: ['Mage'],                 damageType: 'Magic'    },
  lunox:       { id: 'lunox',       name: 'Lunox',       roles: ['Mage'],                 damageType: 'Magic'    },
  harith:      { id: 'harith',      name: 'Harith',      roles: ['Mage'],                 damageType: 'Magic'    },
  kadita:      { id: 'kadita',      name: 'Kadita',      roles: ['Mage', 'Assassin'],     damageType: 'Magic'    },
  lylia:       { id: 'lylia',       name: 'Lylia',       roles: ['Mage'],                 damageType: 'Magic'    },
  cecilion:    { id: 'cecilion',    name: 'Cecilion',    roles: ['Mage'],                 damageType: 'Magic'    },
  luo_yi:      { id: 'luo_yi',      name: 'Luo Yi',      roles: ['Mage'],                 damageType: 'Magic'    },
  yve:         { id: 'yve',         name: 'Yve',         roles: ['Mage'],                 damageType: 'Magic'    },
  valentina:   { id: 'valentina',   name: 'Valentina',   roles: ['Mage'],                 damageType: 'Magic'    },
  xavier:      { id: 'xavier',      name: 'Xavier',      roles: ['Mage'],                 damageType: 'Magic'    },
  novaria:     { id: 'novaria',     name: 'Novaria',     roles: ['Mage'],                 damageType: 'Magic'    },
  zhuxin:      { id: 'zhuxin',      name: 'Zhuxin',      roles: ['Mage'],                 damageType: 'Magic'    },

  // ===== MARKSMEN =====
  miya:        { id: 'miya',        name: 'Miya',        roles: ['Marksman'],             damageType: 'Physical' },
  bruno:       { id: 'bruno',       name: 'Bruno',       roles: ['Marksman'],             damageType: 'Physical' },
  clint:       { id: 'clint',       name: 'Clint',       roles: ['Marksman'],             damageType: 'Physical' },
  layla:       { id: 'layla',       name: 'Layla',       roles: ['Marksman'],             damageType: 'Physical' },
  yi_sun_shin: { id: 'yi_sun_shin', name: 'Yi Sun-shin', roles: ['Assassin', 'Marksman'], damageType: 'Physical' },
  moskov:      { id: 'moskov',      name: 'Moskov',      roles: ['Marksman'],             damageType: 'Physical' },
  karrie:      { id: 'karrie',      name: 'Karrie',      roles: ['Marksman'],             damageType: 'True'     },
  irithel:     { id: 'irithel',     name: 'Irithel',     roles: ['Marksman'],             damageType: 'Physical' },
  lesley:      { id: 'lesley',      name: 'Lesley',      roles: ['Marksman', 'Assassin'], damageType: 'True'     },
  hanabi:      { id: 'hanabi',      name: 'Hanabi',      roles: ['Marksman'],             damageType: 'Physical' },
  claude:      { id: 'claude',      name: 'Claude',      roles: ['Marksman'],             damageType: 'Physical' },
  kimmy:       { id: 'kimmy',       name: 'Kimmy',       roles: ['Marksman', 'Mage'],     damageType: 'Mixed'    },
  granger:     { id: 'granger',     name: 'Granger',     roles: ['Marksman'],             damageType: 'Physical' },
  wanwan:      { id: 'wanwan',      name: 'Wanwan',      roles: ['Marksman'],             damageType: 'Physical' },
  popol_kupa:  { id: 'popol_kupa',  name: 'Popol and Kupa', roles: ['Marksman'],          damageType: 'Physical' },
  brody:       { id: 'brody',       name: 'Brody',       roles: ['Marksman'],             damageType: 'Physical' },
  beatrix:     { id: 'beatrix',     name: 'Beatrix',     roles: ['Marksman'],             damageType: 'Physical' },
  natan:       { id: 'natan',       name: 'Natan',       roles: ['Marksman'],             damageType: 'Magic'    },
  melissa:     { id: 'melissa',     name: 'Melissa',     roles: ['Marksman'],             damageType: 'Physical' },
  ixia:        { id: 'ixia',        name: 'Ixia',        roles: ['Marksman'],             damageType: 'Physical' },

  // ===== SUPPORTS =====
  rafaela:     { id: 'rafaela',     name: 'Rafaela',     roles: ['Support'],              damageType: 'Magic'    },
  estes:       { id: 'estes',       name: 'Estes',       roles: ['Support'],              damageType: 'Magic'    },
  diggie:      { id: 'diggie',      name: 'Diggie',      roles: ['Support'],              damageType: 'Magic'    },
  angela:      { id: 'angela',      name: 'Angela',      roles: ['Support'],              damageType: 'Magic'    },
  kaja:        { id: 'kaja',        name: 'Kaja',        roles: ['Support', 'Fighter'],   damageType: 'Magic'    },
  faramis:     { id: 'faramis',     name: 'Faramis',     roles: ['Support', 'Mage'],      damageType: 'Magic'    },
  carmilla:    { id: 'carmilla',    name: 'Carmilla',    roles: ['Support', 'Tank'],      damageType: 'Magic'    },
  floryn:      { id: 'floryn',      name: 'Floryn',      roles: ['Support'],              damageType: 'Magic'    },

  // ===== 2024-2025 HEROES =====
  chip:        { id: 'chip',        name: 'Chip',        roles: ['Support', 'Tank'],      damageType: 'Magic'    },
  lukas:       { id: 'lukas',       name: 'Lukas',       roles: ['Fighter'],              damageType: 'Physical' },
  sora:        { id: 'sora',        name: 'Sora',        roles: ['Fighter', 'Assassin'],  damageType: 'Physical' },
  kalea:       { id: 'kalea',       name: 'Kalea',       roles: ['Support', 'Fighter'],   damageType: 'Magic'    },
  zetian:      { id: 'zetian',      name: 'Zetian',      roles: ['Mage'],                 damageType: 'Magic'    },
  obsidia:     { id: 'obsidia',     name: 'Obsidia',     roles: ['Marksman', 'Assassin'], damageType: 'Physical' },
};
